theme: minima
title: Michael's Website
github_username:  Mahund
linkedin_username: michael-hund-96432b104
telegram_username: mahund
author: Michael Hund
email: mahund@uc.cl
description: Computer Science student.
