theme: jekyll-theme-minima
name: Michael's website
title: Michael Hund
author: Michael Hund
author_email: mahund@uc.cl
description: Computer Science student.
logo: https://avatars1.githubusercontent.com/u/20783050?s=460&v=4

footer-links:
  github: Mahund
  instagram: michael_hz
  email: mahund@uc.cl
