theme: minima
title: Title
github_username:  Mahund
linkedin_username: michael-hund-96432b104
telegram_username: mahund
name: Name
author: Autor
author_email: Autor mail
email: Email
description: Computer Science student.
logo: https://avatars1.githubusercontent.com/u/20783050?s=460&v=4  
plugins:
 - jekyll-feed
 - jekyll-seo-tag
